// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYoD3lEq7fcwUPkuZAOrDfSY_YYZA101Q',
    appId: '1:432042953718:web:2f9d22031a10fd3dccd5d7',
    messagingSenderId: '432042953718',
    projectId: 'coin-savvy-flutter-project',
    authDomain: 'coin-savvy-flutter-project.firebaseapp.com',
    storageBucket: 'coin-savvy-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyicoYFLbHpkzc3gpTaO6R69ZBqGJJe4Q',
    appId: '1:432042953718:android:54d48fb75ec13711ccd5d7',
    messagingSenderId: '432042953718',
    projectId: 'coin-savvy-flutter-project',
    storageBucket: 'coin-savvy-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUlCqKWsOWG9bEn8HKsSqh7ShQLeSGK8',
    appId: '1:432042953718:ios:7548a0a95bbe8717ccd5d7',
    messagingSenderId: '432042953718',
    projectId: 'coin-savvy-flutter-project',
    storageBucket: 'coin-savvy-flutter-project.appspot.com',
    iosBundleId: 'com.example.coinSavvy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUlCqKWsOWG9bEn8HKsSqh7ShQLeSGK8',
    appId: '1:432042953718:ios:7548a0a95bbe8717ccd5d7',
    messagingSenderId: '432042953718',
    projectId: 'coin-savvy-flutter-project',
    storageBucket: 'coin-savvy-flutter-project.appspot.com',
    iosBundleId: 'com.example.coinSavvy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYoD3lEq7fcwUPkuZAOrDfSY_YYZA101Q',
    appId: '1:432042953718:web:4fa71bb9fbf97d1eccd5d7',
    messagingSenderId: '432042953718',
    projectId: 'coin-savvy-flutter-project',
    authDomain: 'coin-savvy-flutter-project.firebaseapp.com',
    storageBucket: 'coin-savvy-flutter-project.appspot.com',
  );

}